//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBoardTest {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.IngenuityMicro.LedLevel ledLevel;
        
        private Gadgeteer.Modules.GHIElectronics.Display_N18 display_N18;
        
        private Gadgeteer.Modules.GHIElectronics.LED_Strip led_Strip;
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientSP usbClientSP;
        
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        private Gadgeteer.Modules.GHIElectronics.Button button1;
        
        private Gadgeteer.Modules.GHIElectronics.Tunes tunes;
        
        private Gadgeteer.Modules.GHIElectronics.Joystick joystick;
        
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        private Gadgeteer.Modules.GHIElectronics.LightSensor lightSensor;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.led_Strip = new GTM.GHIElectronics.LED_Strip(2);
            this.tunes = new GTM.GHIElectronics.Tunes(3);
            this.button1 = new GTM.GHIElectronics.Button(4);
            this.button = new GTM.GHIElectronics.Button(5);
            this.display_N18 = new GTM.GHIElectronics.Display_N18(6);
            this.ledLevel = new GTM.IngenuityMicro.LedLevel(7);
            this.usbClientSP = new GTM.GHIElectronics.UsbClientSP(8);
        }
    }
}
